config/routes.rb
Rails.application.routes.draw do
  resources :posts
  # get 'home/index'
  root to: "home#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :birtday)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close mr-auto" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <!-- <li><%= link_to t('Edit account'), edit_user_registration_path %></li> -->
  <li><%= link_to t('New Command'), new_command_path %></li>
  <li><%= link_to t('New Category'), new_category_path %></li>
  <li><%= link_to t('Sign out'), destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <!-- <li><%= link_to t('Sign in'), new_user_session_path %></li> -->
  <!-- <li><%= link_to t('Sign up'), new_user_registration_path %></li> -->
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
   <!--  <li><%= link_to t('Users'), users_path %></li> -->
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-lg">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Brand</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <%= link_to t('Home'), root_path, class: 'nav-link' %>
        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
      </li>
      <li class="nav-item">
        <%= link_to t('Sign in'), new_user_session_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to t('Sign out'), destroy_user_session_path, :method=>'delete', class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to t('About'), page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>CodigoComando</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <%= render 'layouts/messages'%>
    <%= render 'layouts/navigation' %>
  </header>
  <body>
    <%= yield %>
      <li><%= link_to t('Sign out'), destroy_user_session_path, :method=>'delete' %></li>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :birtday %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class='page-header'>
  <h1>
    <%= t('Listing Posts') %> (<%= @count_posts %>)  <small><%= @post %></small>
    <div class='pull-right'>
      <%= link_to new_post_path(), class: 'btn btn-info' do %>
        <i class='glyphicon glyphicon-plus'></i> <%= t('New Post') %>
      <% end %>
    </div>
  </h1>
</div>

<table class='table table-hover table-striped' id='datatable'>
  <thead>
  <tr>
      <th>Name</th>
      <th>Birtday</th>
    <th></th>
  </tr>

  </thead>

  <tbody>
    <% @posts.each do |post| %>
    <tr>
        <td><%= post.name %></td>
        <td><%= post.birtday %></td>
      <td class='actions text-center'>
        <%= link_to t('Show'), post_path(post), class: 'btn btn-sm btn-info' %>
        <%= link_to t('Edit'), edit_post_path(post), class: 'btn btn-sm btn-warning' %>
        <%= link_to t('Destroy'), post_path(post), method: :delete, class: 'btn btn-sm btn-danger', data: { confirm: t('Are you sure?') } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Get Foobar!", '#', id: "bar", class: 'button' %><!--

<!--%%= paginate @posts %-->
<script>
  $('#datatable').DataTable();
</script>

app/views/posts/new.html.erb
<div class='page-header'>
  <h1><%= t('New Post') %>
    <div class='pull-right'>
      <%= link_to posts_path, class: 'btn btn-warning' do %>
        <i class='glyphicon glyphicon-backward'></i> <%= t('Back') %>
      <% end %>
    </div>
  </h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class='page-header'>
  <h1>
    <%= t('Post Info') %>
    <div class='pull-right'>
      <%= link_to edit_post_path(@post), class: 'btn btn-info' do %>
        <i class='glyphicon glyphicon-pencil'></i> <%= t('Edit') %>
      <% end %>
      <%= link_to posts_path, class: 'btn btn-warning' do %>
        <i class='glyphicon glyphicon-backward'></i> <%= t('Back') %>
      <% end %>
    </div>
  </h1>
</div>

<div class='panel panel-default'>
  <div class='panel-body'>
    <p>
      <strong>Name</strong>
      <%= @post.name %>
    </p>
    <p>
      <strong>Birtday</strong>
      <%= @post.birtday %>
    </p>
  </div>
</div>